-- Date for Table FACILITY
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('SPORTS HALL','INDOOR','40','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('LEISURE CENTRES','PUBLIC','30','NO','NO');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('SWIMMING','INDOOR','35','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('BASKETBALL','INDOOR','40','NO','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('GYMNASTICS','INDOOR','50','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('FOOTBALL','OUTDOOR','10','NO','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('RUGBU','OUTDOOR','34','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('HEALTH CLUB','PRIVATE','25','NO','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('TENNIS','CENTRES OF EXCELLENCE','60','YES','YES');