-- Data for Table FACILITY
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('SPORTS HALL','INDOOR','40','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('LEISURE CENTRES','PUBLIC','30','NO','NO');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('SWIMMING','INDOOR','35','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('BASKETBALL','INDOOR','40','NO','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('GYMNASTICS','INDOOR','50','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('FOOTBALL','OUTDOOR','10','NO','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('RUGBU','OUTDOOR','34','YES','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('HEALTH CLUB','PRIVATE','25','NO','YES');
INSERT INTO FACILITY (FACILITY_NAME,FACILITY_TYPE,PARKING_SLOTS,DISABLED_PROVISION,VISIBLE) VALUES ('TENNIS','CENTRES OF EXCELLENCE','60','YES','YES');

-- Data for Table CUSTOMER

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, MOBILE, EMAIL_ID, ADDRESS) VALUES ('Srinivas','barre','0499 977976','SRINIVAS557@GMAIL.COM','M11 1234 NICHOLSON ST VIC 3058');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, MOBILE, EMAIL_ID, ADDRESS) VALUES ('suresh','yadav','0458 478 985','suresh.yadav@gmail.com','UNTI 12 SDKJSHD');

-- Data for Table ROLE
INSERT INTO ROLE (ROLE_NAME) VALUES ('SUPERADMIN');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ADMIN');

-- Data for Table PLAN
INSERT INTO PLAN (PLAN_NAME) VALUES ('PLAN1');
INSERT INTO PLAN (PLAN_NAME) VALUES ('PLAN2');

-- Data for Table SERVICE
INSERT INTO SERVICE (NAME,RATE,UOM) VALUES ('SERVICE1',100.05,'UOM1');
INSERT INTO SERVICE (NAME,RATE,UOM) VALUES ('SERVICE2',99.8,'UOM2');

-- Data for Table PLAN_SERVICE_RATE
INSERT INTO PLAN_SERVICE_RATE (PLAN_ID,PLAN_PERIOD,SERVICE_ID,RATE,INCLUDED_AMOUNT,OVERUSAGE_CHARGE,CHARGE_CYCLE) VALUES (1,'MONTHLY',1,12.34,1,0,0);
INSERT INTO PLAN_SERVICE_RATE (PLAN_ID,PLAN_PERIOD,SERVICE_ID,RATE,INCLUDED_AMOUNT,OVERUSAGE_CHARGE,CHARGE_CYCLE) VALUES (2,'HOURLY',2,12.34,1,0,0);

-- Data for Table SUBSCRIPTION
INSERT INTO SUBSCRIPTION (PLAN_ID,SUBSCRIPTION_START_DATE,BILL_CYCLE_DATE,ORDER_ID,STATUS,ACCOUNT_ID,CUSTOMER_ID) VALUES (1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ORDER-01','Active',1,1);
INSERT INTO SUBSCRIPTION (PLAN_ID,SUBSCRIPTION_START_DATE,BILL_CYCLE_DATE,ORDER_ID,STATUS,ACCOUNT_ID,CUSTOMER_ID) VALUES (2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ORDER-02','Cancel',1,1);

-- Data for Table ACCOUNT_CUSTOMER_LINK
INSERT INTO ACCOUNT_CUSTOMER_LINK (ACCOUNT_ID,CUSTOMER_ID) VALUES (1,1);