drop table FACILITY if exists;
CREATE TABLE FACILITY (
	FACILITY_ID NUMBER (10,0) NOT NULL,
	FACILITY_NAME VARCHAR2(30),
	FACILITY_TYPE VARCHAR2(30),
	PARKING_SLOTS VARCHAR2(30),
	DISABLED_PROVISION VARCHAR2(3),
	VISIBLE VARCHAR2(3),
	CONSTRAINT PK_FACILITY PRIMARY KEY (FACILITY_ID)
);

drop table PLAN if exists;
CREATE TABLE PLAN (
	PLAN_ID NUMBER (10,0) NOT NULL,
	PLAN_NAME VARCHAR2(30),
	CONSTRAINT PK_PLAN PRIMARY KEY (PLAN_ID)
);

drop table SERVICE if exists;
CREATE TABLE SERVICE (
	SERVICE_ID NUMBER (10,0) NOT NULL,
	NAME VARCHAR2(30),
	RATE NUMBER (16,2),
	UOM VARCHAR2(30),
	CONSTRAINT PK_SERVICE PRIMARY KEY (SERVICE_ID)
);